-- Plantillas ficticias (nombres verosímiles, no reales) para los clubes de la IA sin plantilla cargada.
-- Determinista por nombre de club; no pisa las plantillas ya cargadas (on conflict do nothing).
insert into public.real_squads (club_name, slot, player_name, position, source_page)
select c, s, f[1 + ((h % nf) + s * 7) % nf] || ' ' || l[1 + ((h2 % nl) + s * 5) % nl],
  case when s < 4 then 'DEL' when s < 8 then 'MED' when s < 11 then 'DEF' else 'ARQ' end, null
from (select unnest(array['San Lorenzo','Racing Club','Estudiantes de La Plata','Rosario Central','Huracán','Ferro Carril Oeste','Colón de Santa Fe','Unión de Santa Fe','Talleres de Córdoba','Tigre','Atlético Tucumán','Sarmiento de Junín','Central Córdoba (SdE)','Deportivo Riestra','Barracas Central','Chacarita Juniors','Quilmes Atlético Club','Atlanta','All Boys','Instituto de Córdoba','San Martín de San Juan','Aldosivi','Patronato','Atlético de Rafaela','Nueva Chicago','Deportivo Morón','Almirante Brown','Temperley','Gimnasia y Esgrima de Jujuy','Olimpo de Bahía Blanca','Defensores de Belgrano','Estudiantes de Buenos Aires','San Telmo','Brown de Adrogué','Tristán Suárez','Chaco For Ever','Independiente Rivadavia','Agropecuario Argentino','Deportivo Maipú','Alvarado de Mar del Plata','Almagro','Atlético Belgrano','Los Andes','Deportivo Español','Arsenal de Sarandí','Colegiales','Talleres de Remedios de Escalada','Comunicaciones','Acassuso','Flandria','Villa Dálmine','Deportivo Armenio','Dock Sud','Argentino de Quilmes','San Miguel','Deportivo Merlo','Sacachispas','Excursionistas','Deportivo Laferrere','Villa San Carlos','UAI Urquiza','Fénix','Cañuelas FC','Cipolletti','Juventud Antoniana','Gimnasia y Tiro de Salta','Douglas Haig','Villa Mitre','Santamarina de Tandil','Central Norte de Salta','Ferrocarril Midland','San Martín de Burzaco','El Porvenir','Berazategui','Luján','Ituzaingó','J.J. de Urquiza','General Lamadrid','Leandro N. Alem','Victoriano Arenas','Central Ballester','Yupanqui','Atlas','Club Mercedes','Real Pilar','Deportivo Camioneros','Juventud Unida de San Miguel','Club Atlético Lugano','Deportivo Paraguayo','Centro Español','Muñiz','Argentino de Rosario','Central Córdoba de Rosario','Defensores de Cambaceres','Puerto Nuevo','Claypole','Sportivo Italiano','Everton de La Plata','Kimberley de Mar del Plata','Gutiérrez Sport Club','Deportivo Rincón','Sol de Mayo','Sarmiento de La Banda','Costa Brava de General Pico','Defensores de Formosa','Altos Hornos Zapla','Jorge Newbery de Comodoro','Germinal de Rawson','Ciudad de Bolívar','Huracán de Comodoro Rivadavia','Boxing Club de Río Gallegos','Guaraní de Paso de los Libres','Racing de Olavarría','Atlético San Jorge','Coronel Aguirre','Deportivo Mandiyú','Huracán de Corrientes','Sportivo Peñarol de San Juan','Juventud Alianza de San Juan','Estudiantes de Resistencia','Bella Vista de Bahía Blanca','Maronese de Neuquén','Independiente de Chivilcoy','El Linqueño','9 de Julio de Rafaela','Huracán Las Heras','Deportivo Central']) c) clubs,
  generate_series(0, 11) s,
  lateral (select array['Lucas','Matías','Nicolás','Facundo','Joaquín','Franco','Gonzalo','Ezequiel','Brian','Maximiliano','Tomás','Agustín','Leandro','Cristian','Emanuel','Santiago','Mateo','Thiago','Bautista','Lautaro','Valentín','Ignacio','Federico','Rodrigo','Sebastián','Martín','Diego','Pablo','Gabriel','Hernán','Máximo','Ramiro','Ariel','Walter','Claudio','Damián','Alan','Axel','Kevin','Jonatan','Marcos','Julián','Esteban','Gastón','Nahuel','Iván','Cristóbal','Lisandro','Fabián','Rubén','Ángel','Sergio','Alejo','Benjamín','Dante','Enzo','Fernando','Guillermo','Horacio','Ismael','Jeremías','Luciano','Manuel','Néstor','Óscar','Patricio','Quique','Raúl','Salvador','Tobías','Ulises','Vicente','Elías','Bruno','Camilo','Darío','Emiliano','Germán','Hugo','Isaías','Jorge','Luis','Nelson'] f, array['Acuña','Barrios','Cabral','Domínguez','Escobar','Figueroa','Godoy','Herrera','Ibarra','Juárez','Luna','Medina','Núñez','Ojeda','Paredes','Quiroga','Rojas','Sandoval','Toledo','Vera','Aguirre','Bustos','Cardozo','Delgado','Echeverría','Fernández','Gallardo','Heredia','Insaurralde','Jiménez','Kuhn','Leiva','Maidana','Navarro','Olivera','Peralta','Quintana','Ramos','Salinas','Tapia','Urquiza','Vargas','Williams','Ybarra','Zárate','Arias','Benítez','Coronel','Duarte','Espinosa','Franco','Giménez','Hidalgo','Ledesma','Maldonado','Nieva','Orellana','Pereyra','Quinteros','Romero','Sosa','Torres','Ugarte','Villalba','Zalazar','Alvarado','Britos','Campos','Díaz','Enríquez','Funes','Guerrero','Hermosilla','Iglesias','Lezcano','Montenegro','Nogueira','Ocampo','Palacios','Rivero','Suárez','Trejo','Ustariz','Velázquez','Aranda','Bogado','Cuello','Dávalos','Ferreyra','Garay','Haedo','Irala','Lencina','Mansilla','Noguera','Ortigoza','Pizarro','Roldán','Segovia','Tévez','Uriarte','Videla','Yáñez','Zabala','Arrieta','Bermúdez','Carrizo','Dorrego','Elizondo','Farías','Galeano','Heinze','Insúa','Jara','Lamas','Molina','Ortiz','Pavón','Ríos','Salvatierra','Taborda','Valdez','Zapata','Albornoz','Bianchi','Chávez','Diez','Escalante','Fleitas','Gaitán','Huerta','Isasi','Juncos','Lagos','Machado','Neira','Olmos','Prieto','Quevedo','Rizzo','Silva','Tello','Vallejos'] l) p,
  lateral (select 83 nf, 143 nl, abs(hashtextextended(c || ':f', 3)) h, abs(hashtextextended(c || ':l', 5)) h2) k
on conflict (club_name, slot) do nothing;
