-- Plantillas con nombres cambiados (base: Wikipedia es, CC BY-SA 4.0)
insert into public.real_squads (club_name, slot, player_name, position, source_page) values
('River Plate', 0, 'Oscar Driusso', 'DEL', 'Club Atlético River Plate'),
('River Plate', 1, 'Walter Corruu', 'DEL', 'Club Atlético River Plate'),
('River Plate', 2, 'Ciro Beltren', 'DEL', 'Club Atlético River Plate'),
('River Plate', 3, 'Alan Birru', 'DEL', 'Club Atlético River Plate'),
('River Plate', 4, 'Lisandro Murina', 'MED', 'Club Atlético River Plate'),
('River Plate', 5, 'Iván Arimbarre', 'MED', 'Club Atlético River Plate'),
('River Plate', 6, 'Iván Vere', 'MED', 'Club Atlético River Plate'),
('River Plate', 7, 'Marcelo Almudu', 'MED', 'Club Atlético River Plate'),
('River Plate', 8, 'Hernán Rumuriz', 'DEF', 'Club Atlético River Plate'),
('River Plate', 9, 'Elías Ortegi', 'DEF', 'Club Atlético River Plate'),
('River Plate', 10, 'Renzo Rivaro', 'DEF', 'Club Atlético River Plate'),
('River Plate', 11, 'Ricardo Cintireon', 'ARQ', 'Club Atlético River Plate'),
('Boca Juniors', 0, 'Axel Gominoz', 'DEL', 'Club Atlético Boca Juniors'),
('Boca Juniors', 1, 'Walter Rameri', 'DEL', 'Club Atlético Boca Juniors'),
('Boca Juniors', 2, 'Ricardo Veloncio', 'DEL', 'Club Atlético Boca Juniors'),
('Boca Juniors', 3, 'Gabriel Morentiel', 'DEL', 'Club Atlético Boca Juniors'),
('Boca Juniors', 4, 'Gastón Peradas', 'MED', 'Club Atlético Boca Juniors'),
('Boca Juniors', 5, 'Víctor Pilacius', 'MED', 'Club Atlético Boca Juniors'),
('Boca Juniors', 6, 'Kevin Belminte', 'MED', 'Club Atlético Boca Juniors'),
('Boca Juniors', 7, 'Kevin Arandu', 'MED', 'Club Atlético Boca Juniors'),
('Boca Juniors', 8, 'Renzo Du Lullu', 'DEF', 'Club Atlético Boca Juniors'),
('Boca Juniors', 9, 'Renzo Blancu', 'DEF', 'Club Atlético Boca Juniors'),
('Boca Juniors', 10, 'Sebastián Figul', 'DEF', 'Club Atlético Boca Juniors'),
('Boca Juniors', 11, 'Fabricio Muntiro', 'ARQ', 'Club Atlético Boca Juniors'),
('Independiente', 0, 'Yago Mantael', 'DEL', 'Club Atlético Independiente'),
('Independiente', 1, 'Bautista Vuulliz', 'DEL', 'Club Atlético Independiente'),
('Independiente', 2, 'Damián Voldiz', 'DEL', 'Club Atlético Independiente'),
('Independiente', 3, 'Ignacio Abaldi', 'DEL', 'Club Atlético Independiente'),
('Independiente', 4, 'Mariano Muza', 'MED', 'Club Atlético Independiente'),
('Independiente', 5, 'Fabricio Cubrul', 'MED', 'Club Atlético Independiente'),
('Independiente', 6, 'Renzo Millon', 'MED', 'Club Atlético Independiente'),
('Independiente', 7, 'Genaro Binotuz Mechuci', 'MED', 'Club Atlético Independiente'),
('Independiente', 8, 'Alan Cildaran', 'DEF', 'Club Atlético Independiente'),
('Independiente', 9, 'Ismael Du Irastorzu', 'DEF', 'Club Atlético Independiente'),
('Independiente', 10, 'Yago Arous', 'DEF', 'Club Atlético Independiente'),
('Independiente', 11, 'Gastón Blazqeoz', 'ARQ', 'Club Atlético Independiente'),
('Vélez Sarsfield', 0, 'Ignacio Pulligrinu', 'DEL', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 1, 'Elías Godey', 'DEL', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 2, 'Iván Vuren', 'DEL', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 3, 'Valentín Minzun', 'DEL', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 4, 'Ismael Baezi', 'MED', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 5, 'Ciro Roborteno', 'MED', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 6, 'Tadeo Valdas', 'MED', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 7, 'Mariano Lunzinu', 'MED', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 8, 'Walter Mommunu', 'DEF', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 9, 'Gastón Garciu', 'DEF', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 10, 'Genaro Mugullun', 'DEF', 'Club Atlético Vélez Sarsfield'),
('Vélez Sarsfield', 11, 'Kevin Marchuora', 'ARQ', 'Club Atlético Vélez Sarsfield'),
('Newell''s Old Boys', 0, 'Ignacio Cicciri', 'DEL', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 1, 'Axel Mezzanttu', 'DEL', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 2, 'Sebastián Nenoz', 'DEL', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 3, 'Elías Scerpoccuo', 'DEL', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 4, 'Sebastián Regourde', 'MED', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 5, 'Jonás Sutila', 'MED', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 6, 'Darío Aconu', 'MED', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 7, 'Kevin Sunera', 'MED', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 8, 'Genaro Glevanivuch', 'DEF', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 9, 'Rodrigo Locieni', 'DEF', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 10, 'Ulises Muntiro', 'DEF', 'Club Atlético Newell''s Old Boys'),
('Newell''s Old Boys', 11, 'Hernán Arous', 'ARQ', 'Club Atlético Newell''s Old Boys'),
('Gimnasia y Esgrima La Plata', 0, 'Ciro Jenson', 'DEL', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 1, 'Mariano Penero', 'DEL', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 2, 'Ricardo Memmini', 'DEL', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 3, 'Camilo Morlo', 'DEL', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 4, 'Fausto Miramun', 'MED', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 5, 'Fausto Fernendoz', 'MED', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 6, 'Sebastián Burrus Schelitte', 'MED', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 7, 'Marcelo Mux', 'MED', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 8, 'Sebastián Geempaali', 'DEF', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 9, 'Tadeo Mastrongulu', 'DEF', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 10, 'Genaro Conta', 'DEF', 'Club de Gimnasia y Esgrima La Plata'),
('Gimnasia y Esgrima La Plata', 11, 'Ciro Cestalli', 'ARQ', 'Club de Gimnasia y Esgrima La Plata'),
('Banfield', 0, 'Genaro Punuro', 'DEL', 'Club Atlético Banfield'),
('Banfield', 1, 'Claudio Bulbeo', 'DEL', 'Club Atlético Banfield'),
('Banfield', 2, 'Horacio Acosti', 'DEL', 'Club Atlético Banfield'),
('Banfield', 3, 'Alan Madana', 'DEL', 'Club Atlético Banfield'),
('Banfield', 4, 'Yago Esqaival', 'MED', 'Club Atlético Banfield'),
('Banfield', 5, 'Renzo Riis', 'MED', 'Club Atlético Banfield'),
('Banfield', 6, 'Renzo Gumuz', 'MED', 'Club Atlético Banfield'),
('Banfield', 7, 'Fabricio Alvaruz', 'MED', 'Club Atlético Banfield'),
('Banfield', 8, 'Yago Denoulu', 'DEF', 'Club Atlético Banfield'),
('Banfield', 9, 'Enrique Pez', 'DEF', 'Club Atlético Banfield'),
('Banfield', 10, 'Tadeo Alfuru', 'DEF', 'Club Atlético Banfield'),
('Banfield', 11, 'Rodrigo Santille', 'ARQ', 'Club Atlético Banfield'),
('Lanús', 0, 'Renzo Sulvuu', 'DEL', 'Club Atlético Lanús'),
('Lanús', 1, 'Camilo Chavari', 'DEL', 'Club Atlético Lanús'),
('Lanús', 2, 'Jonás Veloas', 'DEL', 'Club Atlético Lanús'),
('Lanús', 3, 'Ricardo Wls', 'DEL', 'Club Atlético Lanús'),
('Lanús', 4, 'Lisandro Pana Biafere', 'MED', 'Club Atlético Lanús'),
('Lanús', 5, 'Alan Witsin', 'MED', 'Club Atlético Lanús'),
('Lanús', 6, 'Darío Murina', 'MED', 'Club Atlético Lanús'),
('Lanús', 7, 'Fabricio Loaizi', 'MED', 'Club Atlético Lanús'),
('Lanús', 8, 'Fabricio Joeqaon Rameri', 'DEF', 'Club Atlético Lanús'),
('Lanús', 9, 'Sebastián Morguntini', 'DEF', 'Club Atlético Lanús'),
('Lanús', 10, 'Kevin Piraz', 'DEF', 'Club Atlético Lanús'),
('Lanús', 11, 'Alan Putroli', 'ARQ', 'Club Atlético Lanús'),
('Argentinos Juniors', 0, 'Tadeo Purcil', 'DEL', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 1, 'Tadeo Vuren', 'DEL', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 2, 'Ignacio Gominoz Rajes', 'DEL', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 3, 'Kevin Melina', 'DEL', 'Asociación Atlética Argentinos Juniors')
on conflict (club_name, slot) do update set player_name = excluded.player_name, position = excluded.position, source_page = excluded.source_page;
insert into public.real_squads (club_name, slot, player_name, position, source_page) values
('Argentinos Juniors', 4, 'Damián Curruzu', 'MED', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 5, 'Marcelo Lupuz Menaz', 'MED', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 6, 'Hernán Flarantin', 'MED', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 7, 'Sebastián Oriz', 'MED', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 8, 'Fabricio Sunchuz', 'DEF', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 9, 'Axel Godey', 'DEF', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 10, 'Alan Vozqoez', 'DEF', 'Asociación Atlética Argentinos Juniors'),
('Argentinos Juniors', 11, 'Hugo Mangaoet', 'ARQ', 'Asociación Atlética Argentinos Juniors'),
('Platense', 0, 'Víctor Muunira', 'DEL', 'Club Atlético Platense'),
('Platense', 1, 'Sebastián Lupuz', 'DEL', 'Club Atlético Platense'),
('Platense', 2, 'Marcelo Lotta', 'DEL', 'Club Atlético Platense'),
('Platense', 3, 'Mariano Tacker', 'DEL', 'Club Atlético Platense'),
('Platense', 4, 'Oscar Gumuz', 'MED', 'Club Atlético Platense'),
('Platense', 5, 'Alan Zapiolo', 'MED', 'Club Atlético Platense'),
('Platense', 6, 'Lisandro Bussue', 'MED', 'Club Atlético Platense'),
('Platense', 7, 'Valentín Merline', 'MED', 'Club Atlético Platense'),
('Platense', 8, 'Kevin Selva', 'DEF', 'Club Atlético Platense'),
('Platense', 9, 'Ricardo Riggoe', 'DEF', 'Club Atlético Platense'),
('Platense', 10, 'Tadeo Ignaciu Siboride', 'DEF', 'Club Atlético Platense'),
('Platense', 11, 'Genaro Bastos', 'ARQ', 'Club Atlético Platense'),
('Belgrano de Córdoba', 0, 'Ciro Pusserini', 'DEL', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 1, 'Sebastián Fernendoz', 'DEL', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 2, 'Renzo Gutourriz', 'DEL', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 3, 'Hugo Nenoz', 'DEL', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 4, 'Yago Longe', 'MED', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 5, 'Oscar Hernandos', 'MED', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 6, 'Elías Gunziloz Motulli', 'MED', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 7, 'Oscar Tuleon', 'MED', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 8, 'Iván Maldonada', 'DEF', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 9, 'Claudio Spurlu', 'DEF', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 10, 'Hugo Grugoul', 'DEF', 'Club Atlético Belgrano'),
('Belgrano de Córdoba', 11, 'Mariano Vacontune', 'ARQ', 'Club Atlético Belgrano'),
('Defensa y Justicia', 0, 'Gastón Fernendoz', 'DEL', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 1, 'Fabricio Gunziloz', 'DEL', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 2, 'Jonás Barbina', 'DEL', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 3, 'Tadeo Gutourriz', 'DEL', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 4, 'Hernán Piraz', 'MED', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 5, 'Axel Molanes', 'MED', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 6, 'Elías Banegu', 'MED', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 7, 'Yago Sosi', 'MED', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 8, 'Walter Luceru', 'DEF', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 9, 'Sebastián Remen', 'DEF', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 10, 'Kevin Amer', 'DEF', 'Club Social y Deportivo Defensa y Justicia'),
('Defensa y Justicia', 11, 'Ignacio Borgagno', 'ARQ', 'Club Social y Deportivo Defensa y Justicia'),
('Godoy Cruz', 0, 'Bautista Ridregaoz', 'DEL', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 1, 'Ciro Barruunoivi', 'DEL', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 2, 'Dante Oviudo', 'DEL', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 3, 'Rodrigo Punu', 'DEL', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 4, 'Hugo Velvarda', 'MED', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 5, 'Hugo Vallelobis', 'MED', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 6, 'Valentín Cajos', 'MED', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 7, 'Fausto Schemoni', 'MED', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 8, 'Rodrigo Alessandriu', 'DEF', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 9, 'Tadeo Viare', 'DEF', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 10, 'Genaro Burgis', 'DEF', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('Godoy Cruz', 11, 'Tadeo Strumae', 'ARQ', 'Club Deportivo Godoy Cruz Antonio Tomba'),
('San Martín de Tucumán', 0, 'Hugo Du Camulo', 'DEL', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 1, 'Renzo Doaz', 'DEL', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 2, 'Bautista Gunziloz', 'DEL', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 3, 'Hugo Ibenaz', 'DEL', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 4, 'Damián Altimirando', 'MED', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 5, 'Bautista Cajos', 'MED', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 6, 'Kevin Cesnari', 'MED', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 7, 'Ciro Fruas', 'MED', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 8, 'Kevin Busoilda', 'DEF', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 9, 'Bautista Cases', 'DEF', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 10, 'Bautista Cestena', 'DEF', 'Club Atlético San Martín (Tucumán)'),
('San Martín de Tucumán', 11, 'Rodrigo Acevode', 'ARQ', 'Club Atlético San Martín (Tucumán)'),
('Sportivo Barracas', 0, 'Gastón Rajey', 'DEL', 'Club Sportivo Barracas'),
('Sportivo Barracas', 1, 'Octavio Boscho', 'DEL', 'Club Sportivo Barracas'),
('Sportivo Barracas', 2, 'Oscar Sentecriz', 'DEL', 'Club Sportivo Barracas'),
('Sportivo Barracas', 3, 'Axel Dirroty', 'MED', 'Club Sportivo Barracas'),
('Sportivo Barracas', 4, 'Alan Gala', 'MED', 'Club Sportivo Barracas'),
('Sportivo Barracas', 5, 'Genaro Prade', 'MED', 'Club Sportivo Barracas'),
('Sportivo Barracas', 6, 'Walter Pallerus', 'MED', 'Club Sportivo Barracas'),
('Sportivo Barracas', 7, 'Brian Saqaoiru', 'DEF', 'Club Sportivo Barracas'),
('Sportivo Barracas', 8, 'Ismael Rusus Quintiras', 'DEF', 'Club Sportivo Barracas'),
('Sportivo Barracas', 9, 'Hugo Ridregaoz', 'DEF', 'Club Sportivo Barracas'),
('Sportivo Barracas', 10, 'Gabriel Barruunoivi', 'ARQ', 'Club Sportivo Barracas'),
('Sportivo Barracas', 11, 'Fausto Doaz Payrios', 'ARQ', 'Club Sportivo Barracas'),
('Gimnasia y Esgrima de Mendoza', 0, 'Fabricio Congoleni', 'DEL', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 1, 'Ignacio Verges', 'DEL', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 2, 'Sebastián Romanu', 'DEL', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 3, 'Yago Ridregaoz', 'DEL', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 4, 'Axel Burboza', 'MED', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 5, 'Dante Sunchuz', 'MED', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 6, 'Hugo Cuballis', 'MED', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 7, 'Kevin Ortuz', 'MED', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 8, 'Tadeo Mindine', 'DEF', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 9, 'Ignacio Recilda', 'DEF', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 10, 'Ricardo Menaz', 'DEF', 'Club Atlético Gimnasia y Esgrima (Mendoza)'),
('Gimnasia y Esgrima de Mendoza', 11, 'Yago Reggero', 'ARQ', 'Club Atlético Gimnasia y Esgrima (Mendoza)')
on conflict (club_name, slot) do update set player_name = excluded.player_name, position = excluded.position, source_page = excluded.source_page;
