ALTER TABLE public.players ADD COLUMN IF NOT EXISTS contract_salary int DEFAULT 10000;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS contract_end date;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS agent_id uuid REFERENCES public.agents(id);
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS attr_potential int DEFAULT 70;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS academy_level int DEFAULT 1;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS is_youth boolean DEFAULT false;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS debt int DEFAULT 0;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS stadium_level int DEFAULT 1;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS stadium_condition int DEFAULT 100;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS medical_level int DEFAULT 1;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS store_level int DEFAULT 1;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS board_confidence int DEFAULT 80;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS fans_confidence int DEFAULT 80;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS season_objective text DEFAULT 'Mitad de tabla';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS cohesion int DEFAULT 50;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS authority int DEFAULT 50;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS personality text DEFAULT 'Profesional';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS injury_days int DEFAULT 0;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS injury_type text;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS is_retired boolean DEFAULT false;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS league_tier int DEFAULT 1;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS reputation_level text DEFAULT 'Local';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS is_national_team boolean DEFAULT false;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS national_team_id uuid REFERENCES public.clubs(id);
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS in_international_cup boolean DEFAULT false;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS is_idol boolean DEFAULT false;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS achievements text[] DEFAULT '{}';
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS is_retired boolean DEFAULT false;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.standings ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.offers ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.season_history ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.manager_history ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS nationality text;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS specialization text;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS background text DEFAULT 'STREET_COACH';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS pitch_condition int DEFAULT 60;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS ticket_price numeric DEFAULT 10.0;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS is_user_club boolean DEFAULT true;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS primary_color text DEFAULT '#047857';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS secondary_color text DEFAULT '#FFFFFF';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS badge_id text DEFAULT 'SHIELD';
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS unallocated_perk_points int DEFAULT 0;
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS slot_number int DEFAULT 1;
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS passing_style text DEFAULT 'MIXED';
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS width text DEFAULT 'BALANCED';
ALTER TABLE public.tactics ADD COLUMN IF NOT EXISTS pressing_intensity text DEFAULT 'BALANCED';
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS current_minute int DEFAULT 0;
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS seed text;
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS match_stats jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS simulation_payload jsonb;
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.fixtures ADD COLUMN IF NOT EXISTS finished_at timestamp with time zone;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS division_tier int DEFAULT 5;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS season_year int DEFAULT 2026;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS total_match_days int DEFAULT 38;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS current_match_day int DEFAULT 1;
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS status text DEFAULT 'ACTIVE';
ALTER TABLE public.standings ADD COLUMN IF NOT EXISTS goal_difference int DEFAULT 0;
ALTER TABLE public.standings ADD COLUMN IF NOT EXISTS form text DEFAULT 'E';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS transfer_status text DEFAULT 'NOT_FOR_SALE';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS asking_price numeric(12,2);
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS morale_unhappy_transfer_blocked boolean DEFAULT false;
ALTER TABLE public.offers ADD COLUMN IF NOT EXISTS counter_amount numeric(12,2);
ALTER TABLE public.offers ADD COLUMN IF NOT EXISTS expires_at_week int;
ALTER TABLE public.offers ADD COLUMN IF NOT EXISTS sell_on_fee_percentage int DEFAULT 0;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS release_clause numeric(12,2);
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS negotiation_lockout_week int;
ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS career_id uuid;
ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS personality text DEFAULT 'FAIR';
ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS patience_rating int DEFAULT 50;
ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS base_commission_rate numeric(4,2) DEFAULT 0.08;
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS knowledge_level int DEFAULT 1;
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS perceived_ovr_min int;
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS perceived_ovr_max int;
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS perceived_potential_tier text DEFAULT 'UNKNOWN';
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS pros text[];
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS cons text[];
ALTER TABLE public.scout_reports ADD COLUMN IF NOT EXISTS recommended_action text DEFAULT 'CONSIDER';
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS skill_rating int DEFAULT 10;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS wage_weekly numeric(8,2) DEFAULT 150;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS contract_expires_at date;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS ticket_price numeric(6,2) DEFAULT 10.00;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS consecutive_deficit_weeks int DEFAULT 0;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS financial_status text DEFAULT 'HEALTHY';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS minutes_played_season integer DEFAULT 0 NOT NULL, ADD COLUMN IF NOT EXISTS career_phase text DEFAULT 'PRIME_DEVELOPMENT', ADD COLUMN IF NOT EXISTS announced_retirement_year integer DEFAULT NULL;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS employment_status text DEFAULT 'EMPLOYED' CHECK (employment_status IN ('EMPLOYED', 'UNEMPLOYED', 'RETIRED'));
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS current_contract_wage numeric(10,2) DEFAULT 500.00;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS current_contract_expires_at date;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS personal_savings numeric(12,2) DEFAULT 0.00;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS reputation_rank text DEFAULT 'LOCAL_UNKNOWN' CHECK (reputation_rank IN ('LOCAL_UNKNOWN', 'REGIONAL_PROSPECT', 'ASCENT_SPECIALIST', 'FIRST_TIER_PRO', 'CONTINENTAL_ELITE', 'WORLD_LEGEND'));
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS peak_career_reputation integer DEFAULT 20;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS board_confidence INT DEFAULT 80;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS matches_played INT DEFAULT 0, ADD COLUMN IF NOT EXISTS goals_scored INT DEFAULT 0, ADD COLUMN IF NOT EXISTS assists INT DEFAULT 0, ADD COLUMN IF NOT EXISTS clean_sheets INT DEFAULT 0, ADD COLUMN IF NOT EXISTS club_status VARCHAR(20) DEFAULT 'regular', ADD COLUMN IF NOT EXISTS legend_reason TEXT;
ALTER TABLE public.season_history ADD COLUMN IF NOT EXISTS competition_name VARCHAR(100) DEFAULT 'Liga de Ascenso', ADD COLUMN IF NOT EXISTS promoted BOOLEAN DEFAULT false, ADD COLUMN IF NOT EXISTS relegated BOOLEAN DEFAULT false, ADD COLUMN IF NOT EXISTS champion BOOLEAN DEFAULT false, ADD COLUMN IF NOT EXISTS points INT DEFAULT 0, ADD COLUMN IF NOT EXISTS goals_for INT DEFAULT 0, ADD COLUMN IF NOT EXISTS goals_against INT DEFAULT 0;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS is_retired BOOLEAN DEFAULT false;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS game_date VARCHAR(20) DEFAULT '2026-08-01';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS in_international_cup BOOLEAN DEFAULT false;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS nationality text, ADD COLUMN IF NOT EXISTS specialization text;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS squad_morale INT DEFAULT 70, ADD COLUMN IF NOT EXISTS squad_cohesion INT DEFAULT 70;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS morale INT DEFAULT 70;
ALTER TABLE public.managers ADD COLUMN IF NOT EXISTS national_team_id UUID REFERENCES national_teams(id) ON DELETE SET NULL;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS is_transfer_listed boolean DEFAULT false;
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS training_focus VARCHAR(20) DEFAULT 'EQUILIBRADO';
ALTER TABLE public.clubs ADD COLUMN IF NOT EXISTS training_intensity INT DEFAULT 50;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS injury_risk INT DEFAULT 0;
